../design/rtl_v/dp_bram_byte_we.v
../design/rtl_v/rd_b_fc_infmap.v
../design/rtl_v/wr_b_pool.v
../design/rtl_v/wr_b_fc_scaled.v
../design/rtl_v/cnn_conv_core.v
../design/rtl_v/dp_bram.v
../design/rtl_v/rd_b_weight.v
../design/rtl_v/rd_b_fc_weight.v
../design/rtl_v/cnn_conv_layer.v
../design/rtl_v/rd_b_bias.v
../design/rtl_v/cnn_fc_layer.v
../design/rtl_v/LeNet5_core_ip.v
../design/rtl_v/mem_copy.v
../design/rtl_v/rd_b_infmap.v
../design/rtl_v/LeNet5.v
../design/rtl_v/parallel_mult.v
../design/rtl_v/cnn_fc_core.v
../design/rtl_v/cnn_max_pool.v
../design/rtl_v/dma/dma_ip_control_s_axi.v
../design/rtl_v/dma/dma_wrapper.v
../design/rtl_v/dma/wdma.v
../design/rtl_v/dma/rdma.v
../design/rtl_v/dma/skid_buffer.v
../design/rtl_v/dma/dma_LeNet5_top.v
../design/rtl_v/dma/sync_fifo.v
